version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80"  # Map port 80 of the container to 8000 on the host
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: santok
      DB_PASSWORD: Santok123
    volumes:
      - /home/devops/mylaravel:/var/www/html 
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Santok123
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: santok
      MYSQL_PASSWORD: Santok123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql for initialization
    ports:
      - "3306:3306"  

volumes:
  mysql_data:

